// flow-typed signature: 4365134b9024b55ebd91a4907a889202
// flow-typed version: <<STUB>>/@reach/rect_v0.1.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/rect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/rect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@reach/rect/es/index' {
  declare module.exports: any;
}

declare module '@reach/rect/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@reach/rect/es/index.js' {
  declare module.exports: $Exports<'@reach/rect/es/index'>;
}
declare module '@reach/rect/index' {
  declare module.exports: $Exports<'@reach/rect'>;
}
declare module '@reach/rect/index.js' {
  declare module.exports: $Exports<'@reach/rect'>;
}
declare module '@reach/rect/src/index.js' {
  declare module.exports: $Exports<'@reach/rect/src/index'>;
}
